-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public._prisma_migrations
(
    id character varying(36) COLLATE pg_catalog."default" NOT NULL,
    checksum character varying(64) COLLATE pg_catalog."default" NOT NULL,
    finished_at timestamp with time zone,
    migration_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    logs text COLLATE pg_catalog."default",
    rolled_back_at timestamp with time zone,
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    applied_steps_count integer NOT NULL DEFAULT 0,
    CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public._prisma_migrations
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public."InviteHash"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hash text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "InviteHash_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."InviteHash"
    OWNER to postgres;

REVOKE ALL ON TABLE public."Hash" FROM anon;
REVOKE ALL ON TABLE public."Hash" FROM authenticated;
REVOKE ALL ON TABLE public."Hash" FROM postgres;
REVOKE ALL ON TABLE public."Hash" FROM service_role;

REVOKE ALL ON TABLE public."Children" FROM anon;
REVOKE ALL ON TABLE public."Children" FROM authenticated;
REVOKE ALL ON TABLE public."Children" FROM postgres;
REVOKE ALL ON TABLE public."Children" FROM service_role;

REVOKE ALL ON TABLE public."AccessHashTable" FROM anon;
REVOKE ALL ON TABLE public."AccessHashTable" FROM authenticated;
REVOKE ALL ON TABLE public."AccessHashTable" FROM postgres;
REVOKE ALL ON TABLE public."AccessHashTable" FROM service_role;
