-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

REVOKE ALL ON TABLE public."Hash" FROM authenticated;
REVOKE ALL ON TABLE public."Hash" FROM postgres;
REVOKE ALL ON TABLE public."Hash" FROM service_role;
GRANT ALL ON TABLE public."Hash" TO authenticated;

GRANT ALL ON TABLE public."Hash" TO postgres;

GRANT ALL ON TABLE public."Hash" TO service_role;

REVOKE ALL ON TABLE public."AccessHashTable" FROM authenticated;
REVOKE ALL ON TABLE public."AccessHashTable" FROM postgres;
REVOKE ALL ON TABLE public."AccessHashTable" FROM service_role;
GRANT ALL ON TABLE public."AccessHashTable" TO authenticated;

GRANT ALL ON TABLE public."AccessHashTable" TO postgres;

GRANT ALL ON TABLE public."AccessHashTable" TO service_role;

REVOKE ALL ON TABLE public."Children" FROM authenticated;
REVOKE ALL ON TABLE public."Children" FROM postgres;
REVOKE ALL ON TABLE public."Children" FROM service_role;
GRANT ALL ON TABLE public."Children" TO authenticated;

GRANT ALL ON TABLE public."Children" TO postgres;

GRANT ALL ON TABLE public."Children" TO service_role;
